### ISSUE TITLE
[UberDriverDispatch] "Only one driver can be assigned to a request" is not satisfied

### ISSUE THREAD

**Issue by devanshu0987** [kousiknath/LowLevelDesign#1]
If I understand correctly, we are using a Shared state to control whether a specific request was fulfilled or not. i.e. `DriverThreadSharedState`

Unfortunately, when we spawn threads for each driver in `DispatchThread.dispatch()`, we create a new object of `DriverThreadSharedState` for each individual thread. Which means, each thread operates on its own state.

`List<DriverThread> driverThreads = drivers.stream()
                .map(d -> new DriverThread(d, **new DriverThreadSharedState()**)).toList();`

How to reproduce: 
In the dispatch function, remove the break statement at Line 64 and print all the results for a request. 
For certainty, we can also change the probability of a driver accepting a request to 1.
It should print that multiple drivers were assigned to the same request.

Possible fix:
Initialize a common shared state and pass it to each driver thread.

Please let me know if I can improve on the explanation and can submit a fix for this.

**Comment by kousiknath** [comment]
Hi Devanshu, the issue is genuine. Thanks for spending time and finding this out. I have fixed it.
Also, next time onwards, if you find any such issue, please raise an issue and also you can raise the fix in a separate PR.
